
################################################################################

# This code vectorize HRUs identifier raster file generated by SWAT

# Pennsylvania State University 

# Computational Echohydorlogy Lab - https://compecohydrology-psu.github.io/

# Code developer: Rashid Ansari - rashid.hojjatansari@gmail.com

# Corresponding Author:  Raj Cibin - czr58@psu.edu 

################################################################################

# Set library path here ...

library(sp)

library(raster)

library(sf)

#library(parallel)


setwd(".../data")

shapefile <- st_read("catchment.shp") # NHDPlus catchment shape file

ras<-raster("hru.tif") # HRUs identifier raster file


s <- list()



FUN<-function(i,ras,shapefile){
  
  
  return (extract(ras,shapefile[i,]))
  
  
}


for(i in 1: nrow(shapefile)){
  
  
  s[[i]]<-FUN(i,ras=ras,shapefile=shapefile)
  
}



saveRDS(s,'hru_extract.rds') # This vectorized file is used by NHD_loading.R


